insert into recipe_ingredients (recipe_id, ingredient_name, quantity, unit, category, blw_notes)
select r.id, v.ingredient_name, v.quantity, v.unit, v.category, v.blw_notes
from recipes r
join (values
  ('RF001', 'Arroz', 300, 'g', 'Cereal/hidrato', 'Arroz bem cozido e húmido.'),
  ('RF001', 'Feijão cozido', 500, 'g', 'Leguminosa', 'Feijão muito macio e esmagado.'),
  ('RF001', 'Cenoura', 3, 'un', 'Legume', 'Cenoura bem cozida em palitos ou esmagada.'),
  ('RF001', 'Couve', 150, 'g', 'Legume', 'Couve bem cozinhada e picada.'),
  ('RF001', 'Azeite', 2, 'c. sopa', 'Gordura', 'Usar sem excesso.'),
  ('RF002', 'Massa curta', 320, 'g', 'Cereal/hidrato', 'Massa muito bem cozida.'),
  ('RF002', 'Lentilhas vermelhas', 220, 'g', 'Leguminosa', 'Cozinhar até desfazer em molho.'),
  ('RF002', 'Abóbora', 450, 'g', 'Legume', 'Muito macia e esmagável.'),
  ('RF002', 'Tomate triturado', 400, 'g', 'Legume/fruto', 'Sem sal adicionado.'),
  ('RF003', 'Bacalhau demolhado', 400, 'g', 'Peixe', 'Confirmar espinhas e teor de sal; porção pequena para bebé.'),
  ('RF003', 'Batata', 700, 'g', 'Tubérculo', 'Bem cozida e macia.'),
  ('RF003', 'Cenoura', 3, 'un', 'Legume', 'Bem cozida e esmagável.'),
  ('RF003', 'Bebida vegetal', 250, 'ml', 'Alternativa vegetal', 'Usar bebida vegetal adequada, sem açúcar.'),
  ('RF004', 'Batata', 800, 'g', 'Tubérculo', 'Bem cozida e macia.'),
  ('RF004', 'Grão cozido', 500, 'g', 'Leguminosa', 'Grão esmagado ou triturado.'),
  ('RF004', 'Brócolos', 300, 'g', 'Legume', 'Muito bem cozidos e em floretes macios.'),
  ('RF004', 'Azeite', 2, 'c. sopa', 'Gordura', 'Usar sem excesso.'),
  ('RF006', 'Grão cozido', 400, 'g', 'Leguminosa', 'Grão esmagado ou triturado.'),
  ('RF006', 'Batata-doce', 400, 'g', 'Tubérculo', 'Bem cozida e macia.'),
  ('RF006', 'Cenoura', 3, 'un', 'Legume', 'Bem cozida e esmagável.'),
  ('RF006', 'Couve portuguesa', 120, 'g', 'Legume', 'Bem cozida e picada.'),
  ('RF006', 'Tomate', 200, 'g', 'Legume/fruto', 'Sem sal.'),
  ('RF007', 'Massa espiral', 320, 'g', 'Cereal/hidrato', 'Massa bem cozida.'),
  ('RF007', 'Ervilhas', 250, 'g', 'Leguminosa', 'Esmagar para reduzir risco.'),
  ('RF007', 'Tomate triturado', 400, 'g', 'Legume/fruto', 'Sem sal.'),
  ('RF007', 'Cenoura', 2, 'un', 'Legume', 'Ralada e bem cozinhada.'),
  ('RF008', 'Feijão branco cozido', 600, 'g', 'Leguminosa', 'Bem macio e esmagado.'),
  ('RF008', 'Arroz', 300, 'g', 'Cereal/hidrato', 'Arroz húmido e bem cozido.'),
  ('RF008', 'Cenoura', 3, 'un', 'Legume', 'Bem cozida.'),
  ('RF008', 'Couve lombarda', 200, 'g', 'Legume', 'Bem cozida e picada.'),
  ('RF009', 'Lentilhas cozidas', 500, 'g', 'Leguminosa', 'Bem cozidas e macias.'),
  ('RF009', 'Batata', 900, 'g', 'Tubérculo', 'Puré macio sem sal.'),
  ('RF009', 'Cenoura', 3, 'un', 'Legume', 'Bem cozida no recheio.'),
  ('RF009', 'Tomate triturado', 400, 'g', 'Legume/fruto', 'Sem sal.'),
  ('RF010', 'Pescada', 500, 'g', 'Peixe', 'Sem espinhas; textura macia.'),
  ('RF010', 'Arroz', 280, 'g', 'Cereal/hidrato', 'Arroz malandrinho e macio.'),
  ('RF010', 'Cenoura', 2, 'un', 'Legume', 'Bem cozida.'),
  ('RF010', 'Ervilhas', 200, 'g', 'Leguminosa', 'Esmagar para bebé.'),
  ('RF011', 'Ovos', 6, 'un', 'Ovos', 'Ovo totalmente cozinhado.'),
  ('RF011', 'Batata', 600, 'g', 'Tubérculo', 'Macia em tiras grossas.'),
  ('RF011', 'Ervilhas', 200, 'g', 'Leguminosa', 'Esmagadas.'),
  ('RF011', 'Cenoura', 2, 'un', 'Legume', 'Bem cozida.'),
  ('RF012', 'Grão cozido', 500, 'g', 'Leguminosa', 'Grão esmagado.'),
  ('RF012', 'Abóbora', 500, 'g', 'Legume', 'Macia e esmagável.'),
  ('RF012', 'Couscous', 280, 'g', 'Cereal/hidrato', 'Húmido, não seco.'),
  ('RF012', 'Brócolos', 250, 'g', 'Legume', 'Muito bem cozidos.'),
  ('RF013', 'Massa curta', 350, 'g', 'Cereal/hidrato', 'Massa bem cozida.'),
  ('RF013', 'Lentilhas vermelhas', 220, 'g', 'Leguminosa', 'Desfeitas em molho.'),
  ('RF013', 'Couve-flor', 400, 'g', 'Legume', 'Macia.'),
  ('RF013', 'Tomate triturado', 500, 'g', 'Legume/fruto', 'Sem sal.'),
  ('RF014', 'Feijão preto cozido', 500, 'g', 'Leguminosa', 'Bem esmagado.'),
  ('RF014', 'Batata-doce', 500, 'g', 'Tubérculo', 'Macia.'),
  ('RF014', 'Aveia', 80, 'g', 'Cereal/hidrato', 'Bem hidratada na massa.'),
  ('RF014', 'Arroz', 300, 'g', 'Cereal/hidrato', 'Bem cozido.'),
  ('RF015', 'Pão', 300, 'g', 'Cereal/hidrato', 'Textura húmida, não seca.'),
  ('RF015', 'Grão cozido', 400, 'g', 'Leguminosa', 'Esmagado.'),
  ('RF015', 'Ovos', 4, 'un', 'Ovos', 'Totalmente cozinhados.'),
  ('RF015', 'Couve', 150, 'g', 'Legume', 'Bem cozida e picada.')
) as v(recipe_code, ingredient_name, quantity, unit, category, blw_notes)
on r.code = v.recipe_code
where not exists (
  select 1 from recipe_ingredients ri
  where ri.recipe_id = r.id and ri.ingredient_name = v.ingredient_name
);
