-- Ingredient seeds are intentionally empty.
-- Recipes and ingredients must be imported from external, verifiable sources
-- such as brands, supermarkets, publishers/books, institutions, or official sites.
