with ingredient_seed(recipe_code, ingredient_name, quantity, unit, category, image_url, blw_notes) as (
values
  ('RF001', 'Arroz', 300, 'g', 'Cereal/hidrato', 'https://source.unsplash.com/320x240/?rice', 'Arroz bem cozido e humido.'),
  ('RF001', 'Feijao cozido', 500, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?beans', 'Muito macio e esmagado.'),
  ('RF001', 'Cenoura', 3, 'un', 'Legume', 'https://source.unsplash.com/320x240/?carrot', 'Palitos grandes bem cozidos ou esmagada.'),
  ('RF001', 'Couve', 150, 'g', 'Legume', 'https://source.unsplash.com/320x240/?kale', 'Bem cozinhada e picada.'),
  ('RF001', 'Azeite', 2, 'c. sopa', 'Gordura', 'https://source.unsplash.com/320x240/?olive,oil', 'Usar em pequena quantidade.'),
  ('RF002', 'Massa curta', 320, 'g', 'Cereal/hidrato', 'https://source.unsplash.com/320x240/?pasta', 'Muito bem cozida.'),
  ('RF002', 'Lentilhas vermelhas', 220, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?red,lentils', 'Cozinhar ate desfazer em molho.'),
  ('RF002', 'Abobora', 450, 'g', 'Legume', 'https://source.unsplash.com/320x240/?pumpkin', 'Muito macia e esmagavel.'),
  ('RF002', 'Tomate triturado', 400, 'g', 'Legume/fruto', 'https://source.unsplash.com/320x240/?tomato', 'Sem sal adicionado.'),
  ('RF003', 'Bacalhau demolhado', 400, 'g', 'Peixe', 'https://source.unsplash.com/320x240/?cod,fish', 'Confirmar espinhas e teor de sal; porcao pequena.'),
  ('RF003', 'Batata', 700, 'g', 'Tuberculo', 'https://source.unsplash.com/320x240/?potato', 'Bem cozida e macia.'),
  ('RF003', 'Cenoura', 3, 'un', 'Legume', 'https://source.unsplash.com/320x240/?carrot', 'Bem cozida e esmagavel.'),
  ('RF003', 'Bebida vegetal', 250, 'ml', 'Alternativa vegetal', 'https://source.unsplash.com/320x240/?oat,milk', 'Sem acucar e adequada a bebe.'),
  ('RF004', 'Batata', 800, 'g', 'Tuberculo', 'https://source.unsplash.com/320x240/?potato', 'Bem cozida e macia.'),
  ('RF004', 'Grao cozido', 500, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?chickpeas', 'Esmagado ou triturado.'),
  ('RF004', 'Brocolos', 300, 'g', 'Legume', 'https://source.unsplash.com/320x240/?broccoli', 'Floretes grandes muito bem cozidos.'),
  ('RF004', 'Azeite', 2, 'c. sopa', 'Gordura', 'https://source.unsplash.com/320x240/?olive,oil', 'Usar em pequena quantidade.'),
  ('RF005', 'Lentilhas cozidas', 500, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?lentils', 'Muito macias e esmagadas.'),
  ('RF005', 'Aveia', 80, 'g', 'Cereal/hidrato', 'https://source.unsplash.com/320x240/?oats', 'Bem hidratada na massa.'),
  ('RF005', 'Cenoura', 2, 'un', 'Legume', 'https://source.unsplash.com/320x240/?carrot', 'Ralada e cozinhada.'),
  ('RF005', 'Arroz', 300, 'g', 'Cereal/hidrato', 'https://source.unsplash.com/320x240/?rice', 'Arroz humido e macio.'),
  ('RF005', 'Tomate triturado', 400, 'g', 'Legume/fruto', 'https://source.unsplash.com/320x240/?tomato,sauce', 'Molho sem sal.'),
  ('RF006', 'Grao cozido', 400, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?chickpeas', 'Esmagado ou triturado.'),
  ('RF006', 'Batata-doce', 400, 'g', 'Tuberculo', 'https://source.unsplash.com/320x240/?sweet,potato', 'Bem cozida e macia.'),
  ('RF006', 'Cenoura', 3, 'un', 'Legume', 'https://source.unsplash.com/320x240/?carrot', 'Bem cozida e esmagavel.'),
  ('RF006', 'Couve portuguesa', 120, 'g', 'Legume', 'https://source.unsplash.com/320x240/?kale', 'Bem cozida e picada.'),
  ('RF006', 'Tomate', 200, 'g', 'Legume/fruto', 'https://source.unsplash.com/320x240/?tomato', 'Sem sal.'),
  ('RF007', 'Massa espiral', 320, 'g', 'Cereal/hidrato', 'https://source.unsplash.com/320x240/?fusilli,pasta', 'Bem cozida.'),
  ('RF007', 'Ervilhas', 250, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?peas', 'Esmagar para reduzir risco.'),
  ('RF007', 'Tomate triturado', 400, 'g', 'Legume/fruto', 'https://source.unsplash.com/320x240/?tomato,sauce', 'Sem sal.'),
  ('RF007', 'Cenoura', 2, 'un', 'Legume', 'https://source.unsplash.com/320x240/?carrot', 'Ralada e bem cozinhada.'),
  ('RF008', 'Feijao branco cozido', 600, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?white,beans', 'Bem macio e esmagado.'),
  ('RF008', 'Arroz', 300, 'g', 'Cereal/hidrato', 'https://source.unsplash.com/320x240/?rice', 'Humido e bem cozido.'),
  ('RF008', 'Cenoura', 3, 'un', 'Legume', 'https://source.unsplash.com/320x240/?carrot', 'Bem cozida.'),
  ('RF008', 'Couve lombarda', 200, 'g', 'Legume', 'https://source.unsplash.com/320x240/?cabbage', 'Bem cozida e picada.'),
  ('RF009', 'Lentilhas cozidas', 500, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?lentils', 'Bem cozidas e macias.'),
  ('RF009', 'Batata', 900, 'g', 'Tuberculo', 'https://source.unsplash.com/320x240/?potato', 'Pure macio sem sal.'),
  ('RF009', 'Cenoura', 3, 'un', 'Legume', 'https://source.unsplash.com/320x240/?carrot', 'Bem cozida no recheio.'),
  ('RF009', 'Tomate triturado', 400, 'g', 'Legume/fruto', 'https://source.unsplash.com/320x240/?tomato,sauce', 'Sem sal.'),
  ('RF010', 'Pescada', 500, 'g', 'Peixe', 'https://source.unsplash.com/320x240/?hake,fish', 'Sem espinhas; textura macia.'),
  ('RF010', 'Arroz', 280, 'g', 'Cereal/hidrato', 'https://source.unsplash.com/320x240/?rice', 'Malandrinho e macio.'),
  ('RF010', 'Cenoura', 2, 'un', 'Legume', 'https://source.unsplash.com/320x240/?carrot', 'Bem cozida.'),
  ('RF010', 'Ervilhas', 200, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?peas', 'Esmagar para bebe.'),
  ('RF011', 'Ovos', 6, 'un', 'Ovos', 'https://source.unsplash.com/320x240/?eggs', 'Totalmente cozinhados.'),
  ('RF011', 'Batata', 600, 'g', 'Tuberculo', 'https://source.unsplash.com/320x240/?potato', 'Macia em tiras grossas.'),
  ('RF011', 'Ervilhas', 200, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?peas', 'Esmagadas.'),
  ('RF011', 'Cenoura', 2, 'un', 'Legume', 'https://source.unsplash.com/320x240/?carrot', 'Bem cozida.'),
  ('RF012', 'Grao cozido', 500, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?chickpeas', 'Esmagado.'),
  ('RF012', 'Abobora', 500, 'g', 'Legume', 'https://source.unsplash.com/320x240/?pumpkin', 'Macia e esmagavel.'),
  ('RF012', 'Couscous', 280, 'g', 'Cereal/hidrato', 'https://source.unsplash.com/320x240/?couscous', 'Humido, nao seco.'),
  ('RF012', 'Brocolos', 250, 'g', 'Legume', 'https://source.unsplash.com/320x240/?broccoli', 'Muito bem cozidos.'),
  ('RF013', 'Massa curta', 350, 'g', 'Cereal/hidrato', 'https://source.unsplash.com/320x240/?pasta', 'Bem cozida.'),
  ('RF013', 'Lentilhas vermelhas', 220, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?red,lentils', 'Desfeitas em molho.'),
  ('RF013', 'Couve-flor', 400, 'g', 'Legume', 'https://source.unsplash.com/320x240/?cauliflower', 'Macia.'),
  ('RF013', 'Tomate triturado', 500, 'g', 'Legume/fruto', 'https://source.unsplash.com/320x240/?tomato,sauce', 'Sem sal.'),
  ('RF014', 'Feijao preto cozido', 500, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?black,beans', 'Bem esmagado.'),
  ('RF014', 'Batata-doce', 500, 'g', 'Tuberculo', 'https://source.unsplash.com/320x240/?sweet,potato', 'Macia.'),
  ('RF014', 'Aveia', 80, 'g', 'Cereal/hidrato', 'https://source.unsplash.com/320x240/?oats', 'Bem hidratada na massa.'),
  ('RF014', 'Arroz', 300, 'g', 'Cereal/hidrato', 'https://source.unsplash.com/320x240/?rice', 'Bem cozido.'),
  ('RF015', 'Pao', 300, 'g', 'Cereal/hidrato', 'https://source.unsplash.com/320x240/?bread', 'Textura humida, nao seca.'),
  ('RF015', 'Grao cozido', 400, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?chickpeas', 'Esmagado.'),
  ('RF015', 'Ovos', 4, 'un', 'Ovos', 'https://source.unsplash.com/320x240/?eggs', 'Totalmente cozinhados.'),
  ('RF015', 'Couve', 150, 'g', 'Legume', 'https://source.unsplash.com/320x240/?kale', 'Bem cozida e picada.'),
  ('RF016', 'Lentilhas vermelhas', 260, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?red,lentils', 'Cozinhar ate desfazer.'),
  ('RF016', 'Espinafres', 160, 'g', 'Legume', 'https://source.unsplash.com/320x240/?spinach', 'Bem cozidos e picados.'),
  ('RF016', 'Cenoura', 2, 'un', 'Legume', 'https://source.unsplash.com/320x240/?carrot', 'Macia e esmagavel.'),
  ('RF016', 'Arroz', 280, 'g', 'Cereal/hidrato', 'https://source.unsplash.com/320x240/?rice', 'Muito macio e humido.'),
  ('RF017', 'Quinoa', 260, 'g', 'Cereal/hidrato', 'https://source.unsplash.com/320x240/?quinoa', 'Muito bem cozida e humida.'),
  ('RF017', 'Grao cozido', 400, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?chickpeas', 'Esmagado.'),
  ('RF017', 'Abobora', 400, 'g', 'Legume', 'https://source.unsplash.com/320x240/?pumpkin', 'Muito macia.'),
  ('RF017', 'Brocolos', 250, 'g', 'Legume', 'https://source.unsplash.com/320x240/?broccoli', 'Floretes grandes e macios.'),
  ('RF018', 'Grao cozido', 500, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?chickpeas', 'Bem esmagado.'),
  ('RF018', 'Cenoura', 3, 'un', 'Legume', 'https://source.unsplash.com/320x240/?carrot', 'Cozinhada e macia.'),
  ('RF018', 'Aveia', 80, 'g', 'Cereal/hidrato', 'https://source.unsplash.com/320x240/?oats', 'Bem hidratada.'),
  ('RF018', 'Batata', 700, 'g', 'Tuberculo', 'https://source.unsplash.com/320x240/?potato', 'Palitos grossos e macios.'),
  ('RF019', 'Cevadinha', 300, 'g', 'Cereal/hidrato', 'https://source.unsplash.com/320x240/?barley', 'Muito cozida e cremosa.'),
  ('RF019', 'Ervilhas', 250, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?peas', 'Esmagadas para bebe.'),
  ('RF019', 'Cenoura', 3, 'un', 'Legume', 'https://source.unsplash.com/320x240/?carrot', 'Bem cozida.'),
  ('RF019', 'Azeite', 2, 'c. sopa', 'Gordura', 'https://source.unsplash.com/320x240/?olive,oil', 'Usar sem excesso.'),
  ('RF020', 'Broa', 350, 'g', 'Cereal/hidrato', 'https://source.unsplash.com/320x240/?cornbread', 'Bem humedecida.'),
  ('RF020', 'Feijao frade cozido', 500, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?black,eyed,peas', 'Macio e parcialmente esmagado.'),
  ('RF020', 'Grelos', 250, 'g', 'Legume', 'https://source.unsplash.com/320x240/?turnip,greens', 'Muito cozidos e picados.'),
  ('RF020', 'Azeite', 2, 'c. sopa', 'Gordura', 'https://source.unsplash.com/320x240/?olive,oil', 'Usar em pequena quantidade.'),
  ('RF021', 'Pescada', 450, 'g', 'Peixe', 'https://source.unsplash.com/320x240/?hake,fish', 'Sem espinhas e bem cozida.'),
  ('RF021', 'Ovos', 2, 'un', 'Ovos', 'https://source.unsplash.com/320x240/?eggs', 'Totalmente cozinhados nas pataniscas.'),
  ('RF021', 'Farinha', 100, 'g', 'Cereal/hidrato', 'https://source.unsplash.com/320x240/?flour', 'Cozinhada ate a massa firmar.'),
  ('RF021', 'Arroz', 280, 'g', 'Cereal/hidrato', 'https://source.unsplash.com/320x240/?rice', 'Humido e macio.'),
  ('RF021', 'Cenoura', 2, 'un', 'Legume', 'https://source.unsplash.com/320x240/?carrot', 'Ralada e cozinhada.'),
  ('RF022', 'Feijao manteiga cozido', 550, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?butter,beans', 'Macio e esmagavel.'),
  ('RF022', 'Batata', 650, 'g', 'Tuberculo', 'https://source.unsplash.com/320x240/?potato', 'Cubos grandes bem cozidos.'),
  ('RF022', 'Cenoura', 3, 'un', 'Legume', 'https://source.unsplash.com/320x240/?carrot', 'Macia.'),
  ('RF022', 'Ervilhas', 200, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?peas', 'Esmagadas.'),
  ('RF023', 'Ervilhas', 450, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?peas', 'Bem cozidas e trituradas.'),
  ('RF023', 'Batata', 450, 'g', 'Tuberculo', 'https://source.unsplash.com/320x240/?potato', 'Dah corpo ao creme.'),
  ('RF023', 'Cenoura', 2, 'un', 'Legume', 'https://source.unsplash.com/320x240/?carrot', 'Bem cozida.'),
  ('RF023', 'Ovos', 3, 'un', 'Ovos', 'https://source.unsplash.com/320x240/?eggs', 'Totalmente cozinhados.'),
  ('RF024', 'Salmao', 450, 'g', 'Peixe', 'https://source.unsplash.com/320x240/?salmon', 'Sem espinhas; lascas grandes e humidas.'),
  ('RF024', 'Batata-doce', 650, 'g', 'Tuberculo', 'https://source.unsplash.com/320x240/?sweet,potato', 'Palitos grossos e macios.'),
  ('RF024', 'Couve-flor', 400, 'g', 'Legume', 'https://source.unsplash.com/320x240/?cauliflower', 'Floretes grandes bem cozidos.'),
  ('RF024', 'Azeite', 1, 'c. sopa', 'Gordura', 'https://source.unsplash.com/320x240/?olive,oil', 'Usar em pequena quantidade.'),
  ('RF025', 'Arroz', 300, 'g', 'Cereal/hidrato', 'https://source.unsplash.com/320x240/?rice', 'Muito macio e malandrinho.'),
  ('RF025', 'Tomate triturado', 450, 'g', 'Legume/fruto', 'https://source.unsplash.com/320x240/?tomato,sauce', 'Sem sal.'),
  ('RF025', 'Feijao branco cozido', 500, 'g', 'Leguminosa', 'https://source.unsplash.com/320x240/?white,beans', 'Bem macio e esmagado.'),
  ('RF025', 'Espinafres', 160, 'g', 'Legume', 'https://source.unsplash.com/320x240/?spinach', 'Bem cozidos e picados.')
),
updated as (
  update recipe_ingredients ri
  set
    quantity = v.quantity,
    unit = v.unit,
    category = v.category,
    image_url = v.image_url,
    blw_notes = v.blw_notes
  from recipes r
  join ingredient_seed v on r.code = v.recipe_code
  where ri.recipe_id = r.id
    and ri.ingredient_name = v.ingredient_name
  returning ri.id
)
insert into recipe_ingredients (recipe_id, ingredient_name, quantity, unit, category, image_url, blw_notes)
select r.id, v.ingredient_name, v.quantity, v.unit, v.category, v.image_url, v.blw_notes
from recipes r
join ingredient_seed v on r.code = v.recipe_code
where not exists (
  select 1
  from recipe_ingredients ri
  where ri.recipe_id = r.id
    and ri.ingredient_name = v.ingredient_name
);
