begin;

delete from recipes;

insert into recipes (code, name, category, status, prep_time_min, cook_time_min, cost_level, notes, image_url, source_url)
values
  (
    'RF001',
    'Frango Salteado com Legumes e Cajus',
    'Carne',
    'por_testar',
    10,
    20,
    'medio',
    'Fonte: ALDI Portugal. 1. Temperar o frango conforme a fonte. 2. Saltear no wok com alho e vinho. 3. Juntar brocolos, feijao verde e gengibre. 4. Finalizar com molho de soja, cajus, cebolinho e sesamo.',
    'https://source.unsplash.com/1200x800/?chicken,vegetables,cashew',
    'https://www.aldi.pt/receitas-aldi/refeicao-completa/pratos-principais/frango-salteado-com-legumes-e-cajus.html'
  ),
  (
    'RF002',
    'Empadao de Pescada e Camarao',
    'Peixe',
    'por_testar',
    20,
    40,
    'medio',
    'Fonte: ALDI Portugal. 1. Preparar refogado de alho frances, cebola e alho. 2. Cozinhar pescada com vinho, mostarda e louro. 3. Juntar leite, camarao e espinafres. 4. Montar com pure de batata, queijo e gratinar.',
    'https://source.unsplash.com/1200x800/?fish,pie,shrimp',
    'https://www.aldi.pt/receitas-aldi/refeicao-completa/pratos-principais/empadao-de-pescada-e-camarao.html'
  ),
  (
    'RF003',
    'Penne com Salmao e Espinafres',
    'Peixe',
    'por_testar',
    10,
    20,
    'medio',
    'Fonte: ALDI Portugal. 1. Cozer a massa al dente. 2. Cozinhar o salmao com alho, azeite, limao e especiarias. 3. Juntar espinafres, tomate cherry e natas. 4. Envolver a massa e finalizar com sesamo e cebolinho.',
    'https://source.unsplash.com/1200x800/?salmon,pasta,spinach',
    'https://www.aldi.pt/receitas-aldi/refeicao-completa/pratos-principais/penne-com-salmao-e-espinafres.html'
  ),
  (
    'RF004',
    'Bolonhesa de Lentilhas',
    'Vegetariano',
    'por_testar',
    10,
    20,
    'economico',
    'Fonte: ALDI Portugal. 1. Refogar cebola e alho. 2. Juntar tomate, lentilhas e vinho. 3. Temperar e apurar. 4. Cozer esparguete e servir com a bolonhesa, ervas e queijo.',
    'https://source.unsplash.com/1200x800/?lentil,bolognese,pasta',
    'https://www.aldi.pt/receitas-aldi/refeicao-completa/pratos-principais/bolonhesa-de-lentilhas.html'
  ),
  (
    'RF005',
    'Bacalhau com Arroz Cremoso de Legumes',
    'Peixe',
    'por_testar',
    15,
    25,
    'medio',
    'Fonte: ALDI Portugal. 1. Fazer arroz cremoso com cebola, alho, espargos, ervilhas, vinho e caldo. 2. Assar o bacalhau com azeite, alho e louro. 3. Finalizar o arroz com parmesao e manteiga. 4. Servir com raspa de limao.',
    'https://source.unsplash.com/1200x800/?cod,rice,vegetables',
    'https://www.aldi.pt/receitas-aldi/refeicao-completa/pratos-principais/bacalhau-com-arroz-cremoso-de-legumes.html'
  ),
  (
    'RF006',
    'Arroz de Sardinha',
    'Peixe',
    'por_testar',
    15,
    25,
    'economico',
    'Fonte: ALDI Portugal. 1. Refogar cebola, alho, tomate e pimentos. 2. Cozinhar sardinhas com vinho e ervas. 3. Reservar as sardinhas. 4. Cozer o arroz no caldo e servir com sardinhas, ervas e tomate seco.',
    'https://source.unsplash.com/1200x800/?sardines,rice',
    'https://www.aldi.pt/receitas-aldi/refeicao-completa/pratos-principais/arroz-de-sardinha.html'
  ),
  (
    'RF007',
    'Sopa de Legumes',
    'Sopa',
    'por_testar',
    20,
    20,
    'economico',
    'Fonte: Continente. 1. Lavar e preparar os legumes. 2. Cozer cebola, alho frances, curgete, cenoura e brocolos em agua com sal e azeite. 3. Triturar ate ficar cremosa. 4. Servir com fio de azeite.',
    'https://source.unsplash.com/1200x800/?vegetable,soup',
    'https://feed.continente.pt/receitas/sopa-de-legumes'
  ),
  (
    'RF008',
    'Quinoa com Frango e Legumes',
    'Carne',
    'por_testar',
    10,
    20,
    'medio',
    'Fonte: Knorr Portugal. 1. Temperar cubos de frango com caldo e azeite. 2. Dourar o frango e saltear espargos. 3. Cozer quinoa com caldo. 4. Arrefecer e envolver com legumes, frango, azeite e oregaos.',
    'https://source.unsplash.com/1200x800/?quinoa,chicken,vegetables',
    'https://www.knorr.com/pt/r/quinoa-com-frango-e-legumes.html/208694'
  ),
  (
    'RF009',
    'Salmao no Forno com Espinafres',
    'Peixe',
    'por_testar',
    10,
    20,
    'medio',
    'Fonte: Knorr Portugal. 1. Temperar o salmao. 2. Refogar alho frances em azeite. 3. Preparar molho com sopa de espargos e juntar espinafres. 4. Cozinhar o salmao e terminar no forno.',
    'https://source.unsplash.com/1200x800/?salmon,spinach',
    'https://www.knorr.com/pt/r/salmo-no-forno-com-espinafres.html/208132'
  ),
  (
    'RF010',
    'Caldo Verde',
    'Sopa',
    'por_testar',
    10,
    35,
    'economico',
    'Fonte: Knorr Portugal. 1. Cozer batata, curgete, cebola e alho. 2. Juntar caldo de legumes e cozinhar. 3. Triturar. 4. Acrescentar couve e chourico, ferver e servir com azeite.',
    'https://source.unsplash.com/1200x800/?caldo,verde,soup',
    'https://www.knorr.com/pt/r/caldo-verde.html/213546'
  );

insert into recipe_ingredients (recipe_id, ingredient_name, quantity, unit, category, optional, image_url)
select r.id, i.ingredient_name, i.quantity, i.unit, i.category, i.optional, i.image_url
from recipes r
join (
  values
    ('RF001', 'Peito de frango em cubos', 600, 'g', 'Carne', false, 'https://source.unsplash.com/320x240/?chicken'),
    ('RF001', 'Azeite', null, 'q.b.', 'Gorduras', false, 'https://source.unsplash.com/320x240/?olive,oil'),
    ('RF001', 'Malagueta fresca', 1, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?chili'),
    ('RF001', 'Vinho branco', 1, 'dl', 'Mercearia', false, 'https://source.unsplash.com/320x240/?white,wine'),
    ('RF001', 'Dentes de alho', 3, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?garlic'),
    ('RF001', 'Brocolos', 300, 'g', 'Legumes', false, 'https://source.unsplash.com/320x240/?broccoli'),
    ('RF001', 'Feijao verde', 200, 'g', 'Legumes', false, 'https://source.unsplash.com/320x240/?green,beans'),
    ('RF001', 'Gengibre', null, 'q.b.', 'Legumes', false, 'https://source.unsplash.com/320x240/?ginger'),
    ('RF001', 'Molho de soja', 1, 'dl', 'Mercearia', false, 'https://source.unsplash.com/320x240/?soy,sauce'),
    ('RF001', 'Sementes de sesamo', 1, 'c. sobremesa', 'Mercearia', false, 'https://source.unsplash.com/320x240/?sesame'),
    ('RF001', 'Cebolinho fresco', null, 'q.b.', 'Ervas', false, 'https://source.unsplash.com/320x240/?chives'),
    ('RF001', 'Cajus secos', 300, 'g', 'Frutos secos', false, 'https://source.unsplash.com/320x240/?cashews'),
    ('RF002', 'Azeite', null, 'q.b.', 'Gorduras', false, 'https://source.unsplash.com/320x240/?olive,oil'),
    ('RF002', 'Cebola', 1, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?onion'),
    ('RF002', 'Alho frances', 1, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?leek'),
    ('RF002', 'Dentes de alho', 3, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?garlic'),
    ('RF002', 'Tranches de pescada', 600, 'g', 'Peixe', false, 'https://source.unsplash.com/320x240/?hake,fish'),
    ('RF002', 'Folha de louro', 1, 'un', 'Ervas', false, 'https://source.unsplash.com/320x240/?bay,leaf'),
    ('RF002', 'Vinho branco', 0.5, 'dl', 'Mercearia', false, 'https://source.unsplash.com/320x240/?white,wine'),
    ('RF002', 'Mostarda', 1, 'c. sopa', 'Mercearia', false, 'https://source.unsplash.com/320x240/?mustard'),
    ('RF002', 'Farinha', 1, 'c. sopa', 'Mercearia', false, 'https://source.unsplash.com/320x240/?flour'),
    ('RF002', 'Camarao', 400, 'g', 'Marisco', false, 'https://source.unsplash.com/320x240/?shrimp'),
    ('RF002', 'Leite', 2, 'dl', 'Laticinios', false, 'https://source.unsplash.com/320x240/?milk'),
    ('RF002', 'Espinafres', 150, 'g', 'Legumes', false, 'https://source.unsplash.com/320x240/?spinach'),
    ('RF002', 'Batatas', 1.5, 'kg', 'Legumes', false, 'https://source.unsplash.com/320x240/?potatoes'),
    ('RF002', 'Manteiga', 100, 'g', 'Laticinios', false, 'https://source.unsplash.com/320x240/?butter'),
    ('RF002', 'Queijo da Ilha ralado', 250, 'g', 'Laticinios', false, 'https://source.unsplash.com/320x240/?cheese'),
    ('RF003', 'Massa penne', 300, 'g', 'Mercearia', false, 'https://source.unsplash.com/320x240/?penne,pasta'),
    ('RF003', 'Azeite', null, 'q.b.', 'Gorduras', false, 'https://source.unsplash.com/320x240/?olive,oil'),
    ('RF003', 'Dentes de alho laminados', 4, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?garlic'),
    ('RF003', 'Lombos de salmao sem pele', 400, 'g', 'Peixe', false, 'https://source.unsplash.com/320x240/?salmon'),
    ('RF003', 'Limao', 0.5, 'un', 'Fruta', false, 'https://source.unsplash.com/320x240/?lemon'),
    ('RF003', 'Espinafres frescos', 150, 'g', 'Legumes', false, 'https://source.unsplash.com/320x240/?spinach'),
    ('RF003', 'Natas ligeiras', 1, 'pacote 200 ml', 'Laticinios', false, 'https://source.unsplash.com/320x240/?cream'),
    ('RF003', 'Tomates cherry', 16, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?cherry,tomatoes'),
    ('RF003', 'Sementes de sesamo', null, 'q.b.', 'Mercearia', false, 'https://source.unsplash.com/320x240/?sesame'),
    ('RF003', 'Cebolinho fresco', null, 'q.b.', 'Ervas', false, 'https://source.unsplash.com/320x240/?chives'),
    ('RF004', 'Esparguete', 300, 'g', 'Mercearia', false, 'https://source.unsplash.com/320x240/?spaghetti'),
    ('RF004', 'Queijo Bio', 200, 'g', 'Laticinios', false, 'https://source.unsplash.com/320x240/?cheese'),
    ('RF004', 'Lentilhas cozidas', 600, 'g', 'Leguminosas', false, 'https://source.unsplash.com/320x240/?lentils'),
    ('RF004', 'Cebola', 1, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?onion'),
    ('RF004', 'Dentes de alho', 2, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?garlic'),
    ('RF004', 'Polpa de tomate', 300, 'ml', 'Mercearia', false, 'https://source.unsplash.com/320x240/?tomato,sauce'),
    ('RF004', 'Vinho branco', 200, 'ml', 'Mercearia', false, 'https://source.unsplash.com/320x240/?white,wine'),
    ('RF004', 'Azeite', 50, 'ml', 'Gorduras', false, 'https://source.unsplash.com/320x240/?olive,oil'),
    ('RF004', 'Manjericao e/ou oregaos', null, 'q.b.', 'Ervas', false, 'https://source.unsplash.com/320x240/?basil,oregano'),
    ('RF005', 'Lombos de bacalhau', 2, 'un', 'Peixe', false, 'https://source.unsplash.com/320x240/?cod,fish'),
    ('RF005', 'Dentes de alho', 4, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?garlic'),
    ('RF005', 'Folhas de louro', 2, 'un', 'Ervas', false, 'https://source.unsplash.com/320x240/?bay,leaf'),
    ('RF005', 'Azeite', null, 'q.b.', 'Gorduras', false, 'https://source.unsplash.com/320x240/?olive,oil'),
    ('RF005', 'Espargos', 150, 'g', 'Legumes', false, 'https://source.unsplash.com/320x240/?asparagus'),
    ('RF005', 'Ervilhas', 50, 'g', 'Legumes', false, 'https://source.unsplash.com/320x240/?peas'),
    ('RF005', 'Cebola', 0.5, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?onion'),
    ('RF005', 'Arroz agulha', 1, 'chavena', 'Mercearia', false, 'https://source.unsplash.com/320x240/?rice'),
    ('RF005', 'Vinho branco', 0.33, 'chavena', 'Mercearia', false, 'https://source.unsplash.com/320x240/?white,wine'),
    ('RF005', 'Caldo de legumes', 4, 'chavenas', 'Mercearia', false, 'https://source.unsplash.com/320x240/?vegetable,stock'),
    ('RF005', 'Queijo parmesao ralado', 0.5, 'chavena', 'Laticinios', false, 'https://source.unsplash.com/320x240/?parmesan'),
    ('RF005', 'Manteiga', 1, 'c. sopa', 'Laticinios', false, 'https://source.unsplash.com/320x240/?butter'),
    ('RF005', 'Limao', 1, 'un', 'Fruta', false, 'https://source.unsplash.com/320x240/?lemon'),
    ('RF006', 'Azeite', 3, 'c. sopa', 'Gorduras', false, 'https://source.unsplash.com/320x240/?olive,oil'),
    ('RF006', 'Cebola', 1, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?onion'),
    ('RF006', 'Dentes de alho', 2, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?garlic'),
    ('RF006', 'Tomates maduros pelados', 2, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?tomatoes'),
    ('RF006', 'Pimento verde e vermelho', 100, 'g', 'Legumes', false, 'https://source.unsplash.com/320x240/?bell,pepper'),
    ('RF006', 'Salsa', 1, 'ramo', 'Ervas', false, 'https://source.unsplash.com/320x240/?parsley'),
    ('RF006', 'Coentros', 1, 'ramo', 'Ervas', false, 'https://source.unsplash.com/320x240/?cilantro'),
    ('RF006', 'Piri-piri', 1, 'un', 'Especiarias', false, 'https://source.unsplash.com/320x240/?chili'),
    ('RF006', 'Folha de louro', 1, 'un', 'Ervas', false, 'https://source.unsplash.com/320x240/?bay,leaf'),
    ('RF006', 'Sardinhas arranjadas', 12, 'un', 'Peixe', false, 'https://source.unsplash.com/320x240/?sardines'),
    ('RF006', 'Vinho branco', 1, 'dl', 'Mercearia', false, 'https://source.unsplash.com/320x240/?white,wine'),
    ('RF006', 'Arroz carolino', 400, 'g', 'Mercearia', false, 'https://source.unsplash.com/320x240/?rice'),
    ('RF006', 'Agua quente', 1.2, 'l', 'Mercearia', false, 'https://source.unsplash.com/320x240/?water'),
    ('RF006', 'Tomates secos', null, 'q.b.', 'Mercearia', false, 'https://source.unsplash.com/320x240/?sun,dried,tomatoes'),
    ('RF007', 'Cebola laminada', 1, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?onion'),
    ('RF007', 'Dente de alho', 1, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?garlic'),
    ('RF007', 'Alho frances laminado', 0.5, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?leek'),
    ('RF007', 'Curgete em pedacos', 1, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?zucchini'),
    ('RF007', 'Cenouras em pedacos', 3, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?carrots'),
    ('RF007', 'Brocolos em pedacos', 0.5, 'cabeca', 'Legumes', false, 'https://source.unsplash.com/320x240/?broccoli'),
    ('RF007', 'Sal', 1, 'c. cafe', 'Temperos', false, 'https://source.unsplash.com/320x240/?salt'),
    ('RF007', 'Azeite', null, 'q.b.', 'Gorduras', false, 'https://source.unsplash.com/320x240/?olive,oil'),
    ('RF008', 'Peitos de frango em cubos', 2, 'un', 'Carne', false, 'https://source.unsplash.com/320x240/?chicken'),
    ('RF008', 'Quinoa branca', 100, 'g', 'Mercearia', false, 'https://source.unsplash.com/320x240/?quinoa'),
    ('RF008', 'Quinoa vermelha', 100, 'g', 'Mercearia', false, 'https://source.unsplash.com/320x240/?red,quinoa'),
    ('RF008', 'Agua', 400, 'ml', 'Mercearia', false, 'https://source.unsplash.com/320x240/?water'),
    ('RF008', 'Knorr Caldo Vitalie de Galinha', 2, 'cubos', 'Mercearia', false, 'https://source.unsplash.com/320x240/?stock,cube'),
    ('RF008', 'Espargos frescos', 1, 'molho', 'Legumes', false, 'https://source.unsplash.com/320x240/?asparagus'),
    ('RF008', 'Pimento vermelho', 1, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?red,pepper'),
    ('RF008', 'Cebola roxa', 1, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?red,onion'),
    ('RF008', 'Tomate cereja', 250, 'g', 'Legumes', false, 'https://source.unsplash.com/320x240/?cherry,tomatoes'),
    ('RF008', 'Azeite', null, 'q.b.', 'Gorduras', false, 'https://source.unsplash.com/320x240/?olive,oil'),
    ('RF008', 'Oregaos secos', null, 'q.b.', 'Ervas', false, 'https://source.unsplash.com/320x240/?oregano'),
    ('RF009', 'Lombos de salmao', 4, 'un', 'Peixe', false, 'https://source.unsplash.com/320x240/?salmon'),
    ('RF009', 'Alho frances em rodelas', 1, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?leek'),
    ('RF009', 'Knorr Sopa de Espargos', 1, 'embalagem 70 g', 'Mercearia', false, 'https://source.unsplash.com/320x240/?asparagus,soup'),
    ('RF009', 'Espinafres frescos', 1, 'embalagem 200 g', 'Legumes', false, 'https://source.unsplash.com/320x240/?spinach'),
    ('RF009', 'Azeite', 2, 'c. sopa', 'Gorduras', false, 'https://source.unsplash.com/320x240/?olive,oil'),
    ('RF009', 'Sal', null, 'q.b.', 'Temperos', false, 'https://source.unsplash.com/320x240/?salt'),
    ('RF009', 'Pimenta rosa em graos', null, 'q.b.', 'Especiarias', false, 'https://source.unsplash.com/320x240/?pink,pepper'),
    ('RF010', 'Batata', 1, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?potato'),
    ('RF010', 'Curgete', 1, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?zucchini'),
    ('RF010', 'Cebolas', 2, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?onion'),
    ('RF010', 'Dente de alho', 1, 'un', 'Legumes', false, 'https://source.unsplash.com/320x240/?garlic'),
    ('RF010', 'Knorr Caldo de Legumes', 1, 'cubo 10 g', 'Mercearia', false, 'https://source.unsplash.com/320x240/?vegetable,stock'),
    ('RF010', 'Couve lombardo', 200, 'g', 'Legumes', false, 'https://source.unsplash.com/320x240/?cabbage'),
    ('RF010', 'Chourico', 8, 'rodelas', 'Charcutaria', false, 'https://source.unsplash.com/320x240/?sausage'),
    ('RF010', 'Azeite', null, 'q.b.', 'Gorduras', false, 'https://source.unsplash.com/320x240/?olive,oil')
) as i(code, ingredient_name, quantity, unit, category, optional, image_url)
on r.code = i.code;

commit;